// Copyright 2026 zstdf contributors. SPDX-License-Identifier: Apache-2.0
'use strict';
// The workspace uses the same bounded query contract for the local service and
// self-contained snapshots. Source labels are always text, never executable HTML.
(()=>{
const boot=JSON.parse(document.getElementById('viewer-boot').textContent),$=id=>document.getElementById(id),T=(s,v)=>window.ReportUI?.t(s,v)||s;
const colors=['#287bb5','#d85d34','#44946b','#a160af','#bd921d','#388f9c','#cc6192','#716ac7'];
const esc=v=>String(v??'[null]').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v==null?'[null]':typeof v==='number'?Number.isInteger(v)?String(v):Number(v.toPrecision(7)).toString():typeof v==='object'?JSON.stringify(v):String(v);
const numeric=v=>v&&typeof v==='object'&&'value'in v?v.value:v;
const utc=v=>v==null?'[null]':new Date(Number(v)*1000).toISOString().replace('T',' ').replace('.000Z',' UTC');
const clone=v=>JSON.parse(JSON.stringify(v));
const defaults={pane:0,table:'measurements',population:'latest',run:null,wafer:null,sites:[],tests:[],attempts:[],excluded_measurements:[],excluded_devices:[],filters:{},sort:'',descending:false,offset:0,limit:80,plot:'histogram',bins:20,low_whisker:2,high_whisker:98,color:'site',level:'hard_bin',show_pass:false,statistic:'mean',hard_bins:[],soft_bins:[],alerts:{},annotation:"all",search:"",values:{}};
const state={q:{...clone(defaults),...(boot.query||{})},selection:{tests:[],attempts:[],hard_bins:[],soft_bins:[]},nav:'tests',navOffset:0,navSelected:[],panes:[],next:1,revision:0};
const labels={information:'Information',tests:'Tests',devices:'Devices',wafers:'Wafers',hard_bin:'Hard Bins',soft_bin:'Soft Bins',measurements:'Data Log',records:'Records',histogram:'Histogram',box:'Box',probability:'Probability',trend:'Trend',scatter:'Scatter',range:'Range',pareto:'Pareto',binmap:'Bin Wafer Map',paramap:'Parametric Wafer Map',timing:'Timing summary',ffc:'FFC Pareto'};
const headings={test_method:'Test method',foreground_time:'Foreground time',background_time:'Background time',id:'Row',record:'Record',attempt:'Attempt',run:'Run',kind:'Type',number:'Test number',name:'Test name',channel:'Result index',pattern:'Pattern',head:'Head',site:'Site',lot:'Lot',wafer:'Wafer',x:'X',y:'Y',part:'Part ID',ecid:'Device identity',start:'MIR START_T',passed:'Pass/Fail',hard_bin:'Hard bin',soft_bin:'Soft bin',duration:'Duration (ms)',value:'Value',raw:'Raw value',value_state:'Value status',low:'Low',high:'High',units:'Units',flags:'Flags',alarm:'Alarm',offset:'Offset',latest:'Latest',first:'First',last_execution:'Last execution',issue:'Issue',eav_fragment:'Parquet fragment',eav_row:'Parquet row'};
function fail(e){$('message').textContent=e.message||String(e);}
function clearError(){$('message').textContent='';}
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function modal(title,html){const d=$('dialog');d.innerHTML=`<div style="display:flex;align-items:center"><h2 style="flex:1">${esc(T(title))}</h2><button id="close-dialog">×</button></div>${html}`;d.querySelector('#close-dialog').onclick=()=>d.close();if(!d.open)d.showModal();window.ReportUI?.translate(d);return d;}
async function api(command,q){if(boot.offline)return offline(command,q);const r=await fetch(window.VIEWER_API+command,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)});if(!r.ok){const v=await r.json();throw Error(v.error||r.statusText);}return command==='export'?r.text():r.json();}
function population(r,q){return q.population==='all'||r[q.population]===true;}
function scope(r,q){return(q.run==null||r.run===q.run)&&(q.wafer==null||r.wafer===q.wafer)&&(!q.sites.length||q.sites.includes(r.site))&&(['devices','records'].includes(q.table)||!q.tests.length||q.tests.includes(r.test))&&(!q.attempts.length||q.attempts.includes(r.attempt))&&(!q.hard_bins.length||q.hard_bins.includes(r.hard_bin))&&(!q.soft_bins.length||q.soft_bins.includes(r.soft_bin));}
function matches(r,filters){return Object.entries(filters||{}).every(([k,f])=>{f=f.trim();if(!f)return true;const m=f.match(/^(>=|<=|!=|>|<|=)(.*)$/);const v=r[k];if(m){const rhs=m[2].trim(),n=Number(rhs),op=m[1];if(typeof v==='number'&&Number.isFinite(n))return op==='>='?v>=n:op==='<='?v<=n:op==='>'?v>n:op==='<'?v<n:op==='!='?v!==n:v===n;return op==='!='?fmt(v)!==rhs:op==='='&&fmt(v)===rhs;}return fmt(v).toLowerCase().includes(f.toLowerCase());});}
function included(r,q,measure=true){return population(r,q)&&!q.excluded_devices.includes(r.attempt)&&(!measure||!q.excluded_measurements.includes(r.id));}
function offlineRows(q,analysis=false){const list=q.table==='devices'?boot.devices||[]:q.table==='records'?Object.values(boot.evidence||{}).map(e=>({...((boot.devices||[]).find(r=>r.id===e.attempt)||{}),...e,record:e.id})):boot.rows||[];return list.filter(r=>scope(r,q)&&(q.plot!=='timing'||included(r,q,false))&&(analysis?included(r,q,q.table!=='devices')&&(q.table==='devices'||r.last_execution):q.table!=='measurements'||population(r,q)));}
function display(r,q){return matches(r,q.filters)&&Object.entries(q.values||{}).every(([k,vs])=>vs.some(v=>JSON.stringify(v)===JSON.stringify(r[k]??null)))&&(!q.search||JSON.stringify(r).toLowerCase().includes(q.search.toLowerCase()));}
function cmp(a,b){return typeof a==='number'&&typeof b==='number'?a-b:fmt(a).localeCompare(fmt(b));}
function quantile(a,p){if(!a.length)return null;const rank=(a.length-1)*p/100,i=Math.floor(rank),f=rank-i;return a[i]+f*(a[Math.ceil(rank)]-a[i]);}
function offlinePlot(q){
 const rows=offlineRows({...q,table:['binmap'].includes(q.plot)||q.plot==='pareto'&&['hard_bin','soft_bin'].includes(q.level)?'devices':'measurements'},true);
 if(q.plot==='binmap'||q.plot==='paramap')return{cells:rows.filter(r=>r.x!=null&&r.y!=null&&r.wafer!=null),missing_coordinates:rows.filter(r=>r.x==null||r.y==null||r.wafer==null).length,population:q.population};
 if(q.plot==='pareto'){
  const bins=['hard_bin','soft_bin'].includes(q.level),unique=new Map;
  for(const r of rows){if(!bins&&r.channel!=null||q.level==='pattern'&&r.kind!=='FTR')continue;const label=bins?fmt(r[q.level]):q.level==='pattern'?r.pattern||'[null]':`${r.kind} ${r.number||0} ${r.name}`,key=JSON.stringify([label,r.attempt]),group=q.color==='site'?`${r.head}/${r.site}`:q.color==='wafer'?fmt(r.wafer):q.color==='lot'?r.lot:'All';const old=unique.get(key);unique.set(key,{label,group,passed:!old?r.passed:old.passed===false||r.passed===false?false:old.passed===true&&r.passed===true?true:null});}
  const modes=new Map;for(const v of unique.values()){const a=modes.get(v.label)||{label:v.label,count:0,pass:0,fail:0,unknown:0,groups:{}};a[v.passed==null?'unknown':v.passed?'pass':'fail']++;if(bins||v.passed===false){a.count++;a.groups[v.group]=(a.groups[v.group]||0)+1;}modes.set(v.label,a);}return{modes:[...modes.values()].filter(v=>bins?q.show_pass||v.fail||v.unknown:v.count).sort((a,b)=>b.count-a.count),population:q.population};
 }
 if(q.plot==='scatter'&&q.tests.length===2){const pairs=new Map;for(const r of rows)if(r.value!=null){const a=pairs.get(r.attempt)||{};if(!a[r.test]||a[r.test].record<r.record)a[r.test]=r;pairs.set(r.attempt,a);}const points=[];let unpaired=0;for(const a of pairs.values()){const x=a[q.tests[0]],y=a[q.tests[1]];if(x&&y)points.push({x:x.value,y:y.value,record:x.record,other_record:y.record,attempt:x.attempt,site:x.site});else unpaired++;}const mx=points.reduce((a,p)=>a+p.x,0)/points.length,my=points.reduce((a,p)=>a+p.y,0)/points.length,xx=points.reduce((a,p)=>a+(p.x-mx)**2,0),yy=points.reduce((a,p)=>a+(p.y-my)**2,0),xy=points.reduce((a,p)=>a+(p.x-mx)*(p.y-my),0);return{points,count:points.length,unpaired,correlation:points.length>1&&xx&&yy?xy/Math.sqrt(xx*yy):null,sampled:false,population:q.population};}
 const bounds={};for(const r of rows)if(r.value!=null){const b=bounds[r.units]??=[r.value,r.value];b[0]=Math.min(b[0],r.value);b[1]=Math.max(b[1],r.value);}for(const b of Object.values(bounds))if(b[0]===b[1]){b[0]-=.5;b[1]+=.5;}
 const groups={};for(const r of rows){const key=JSON.stringify([r.test,q.color==='site'?`${r.head}/${r.site}`:'',r.units]);(groups[key]??=[]).push(r);}const series={};for(const [key,records]of Object.entries(groups)){const pts=records.filter(r=>r.value!=null),vals=pts.map(r=>r.value).sort((a,b)=>a-b),count=vals.length,mean=count?vals.reduce((a,b)=>a+b,0)/count:0,m2=vals.reduce((a,b)=>a+(b-mean)**2,0),sigma=count>1?Math.sqrt(m2/(count-1)):null,min=vals[0]??null,max=vals.at(-1)??null,histogram=Array(q.bins).fill(0),[hist_min,hist_max]=bounds[pts[0]?.units]||[0,1];for(const v of vals)histogram[Math.min(q.bins-1,Math.floor((v-hist_min)/(hist_max-hist_min)*q.bins))]++;const sorted=[...pts].sort((a,b)=>a.value-b.value),cdf=[];for(let i=0;i<sorted.length;){let end=i+1;while(end<sorted.length&&sorted[end].value===sorted[i].value)end++;cdf.push({...sorted[i],probability:end/count*100});i=end;}const low=pts[0]?.low??null,high=pts[0]?.high??null,variable_limits=pts.some(r=>r.low!==low||r.high!==high);series[key]={count,invalid:records.filter(r=>r.value==null&&!['missing','nonfinite','not_numeric'].includes(r.value_state)).length,missing:records.filter(r=>r.value_state==='missing').length,nonfinite:records.filter(r=>r.value_state==='nonfinite').length,not_numeric:records.filter(r=>r.value_state==='not_numeric').length,mean,min,max,m2,sigma,quantiles:count?[q.low_whisker,25,50,75,q.high_whisker].map(p=>quantile(vals,p)):[],histogram:count?histogram:[],hist_min,hist_max,cdf,low,high,variable_limits,units:pts[0]?.units||'',points:pts,sampled:false,ppk:!variable_limits&&sigma>0&&low!=null&&high>low?Math.min(high-mean,mean-low)/(3*sigma):null};}return{series,population:q.population,exact_statistics:true,quantile_method:'linear interpolation',sigma_method:'sample standard deviation'};
}
async function offline(command,q){
 if(command==='inspect'){const evidence=boot.evidence?.[q.id];if(!evidence)throw Error(T('Record detail is not included in this snapshot'));return{evidence,hex:boot.raw_hex?.[q.id]};}
 if(command==='export')throw Error(T('Use the existing HTML attachment or export CSV/JSON'));
 if(boot.scope==='summary'){if(command==='plot'){const plot=boot.pane_plots?.[q.pane]||boot.plots[q.plot];if(!plot)throw Error(T('This plot is not included in the summary snapshot'));if(plot.unavailable)throw Error(plot.unavailable);return plot;}if(command==='rows'&&q.table==='tests')return{...boot.summaries,rows:boot.summaries.rows.slice(q.offset,q.offset+q.limit)};throw Error(T('Summary snapshot has no record drilldown'));}
 if(command==='distinct'){const input={...q.query,filters:{...q.query.filters},values:{...q.query.values}};delete input.filters[q.field];delete input.values[q.field];const map=new Map;for(const r of offlineRows(input).filter(r=>display(r,input))){const value=r[q.field]??null,key=JSON.stringify(value);const a=map.get(key)||{value,count:0};a.count++;map.set(key,a);}if(map.size>10000)throw Error(T('Use a text filter for this column'));return{values:[...map.values()]};}
 if(command==='plot'){const data=offlinePlot(q),rows=offlineRows({...q,table:q.plot==='binmap'||q.plot==='pareto'&&['hard_bin','soft_bin'].includes(q.level)?'devices':'measurements'}).filter(r=>q.plot==='binmap'||q.plot==='pareto'&&['hard_bin','soft_bin'].includes(q.level)||r.last_execution);return{...data,included:rows.filter(r=>included(r,q,q.plot!=='binmap'&&!(q.plot==='pareto'&&['hard_bin','soft_bin'].includes(q.level)))).length,excluded:rows.filter(r=>!included(r,q,q.plot!=='binmap'&&!(q.plot==='pareto'&&['hard_bin','soft_bin'].includes(q.level)))).length};}
 if(command==='data-export')return{source_hash:boot.manifest.source_hash,query:q,rows:offlineRows(q).filter(r=>display(r,q))};
 if(['tests','wafers','hard_bin','soft_bin'].includes(q.table)){const groups=new Map,input={...q,table:q.table==='tests'?'measurements':'devices',tests:[]};for(const r of offlineRows(input,true)){const key=q.table==='tests'?r.test:fmt(r[q.table==='wafers'?'wafer':q.table]);const name=q.table==='tests'?`${r.kind} ${r.number??''} ${r.name}${r.channel==null?'':` [result ${r.channel}]`}`:key;const a=groups.get(key)||{key,name,count:0,pass:0,fail:0,unknown:0,min:null,max:null,sum:0,numeric:0,units:r.units};a.count++;a[r.passed==null?'unknown':r.passed?'pass':'fail']++;if(r.value!=null){a.min=a.min==null?r.value:Math.min(a.min,r.value);a.max=a.max==null?r.value:Math.max(a.max,r.value);a.sum+=r.value;a.numeric++;}a.mean=a.numeric?a.sum/a.numeric:null;groups.set(key,a);}const rows=[...groups.values()].filter(r=>!q.search||JSON.stringify(r).toLowerCase().includes(q.search.toLowerCase())).sort((a,b)=>cmp(a[q.sort||'name'],b[q.sort||'name'])*(q.descending?-1:1));return{rows:rows.slice(q.offset,q.offset+q.limit),total:rows.length,population:q.population};}
 const all=offlineRows(q),rows=all.filter(r=>display(r,q)).sort((a,b)=>(q.sort?cmp(a[q.sort],b[q.sort]):a.record-b.record||a.id-b.id)*(q.descending?-1:1));
 const annotations=rows.flatMap((r,index)=>{const a={id:r.id,index,failed:r.passed===false,alarm:r.alarm,excluded:(q.table==='devices'?q.excluded_devices:q.excluded_measurements).includes(r.id),alert:Object.keys(q.alerts).length>0&&matches(r,q.alerts)};return(q.annotation==='failure'?a.failed:q.annotation==='alarm'?a.alarm:q.annotation==='exclusion'?a.excluded:q.annotation==='alert'?a.alert:a.failed||a.alarm||a.excluded||a.alert)?[a]:[];});
 return{rows:rows.slice(q.offset,q.offset+q.limit),total:rows.length,timing_summary:{count:all.filter(r=>r.duration!=null).length,sum_ms:all.reduce((n,r)=>n+(r.duration||0),0),missing:all.filter(r=>r.duration==null).length},included:all.filter(r=>included(r,q)).length,offset:q.offset,population:q.population,annotations:annotations.slice(0,2000),annotation_count:annotations.length,next_annotation:annotations.find(a=>a.index>q.offset)?.index??null,previous_annotation:annotations.filter(a=>a.index<q.offset).at(-1)?.index??null};
}
function paneQuery(p){return{...clone(state.q),pane:p.id,...(p.linked?state.selection:p.selection),...clone(p.options),table:p.kind==='devices'?'devices':p.kind==='records'?'records':'measurements',plot:p.kind,filters:p.filters,sort:p.sort,descending:p.descending,offset:p.offset,limit:80,values:p.values||{}};}
function button(label,action,title=label){const b=document.createElement('button');b.textContent=T(label);b.title=T(title);b.onclick=action;return b;}
function addPane(kind='measurements',selection=state.selection){if(state.panes.length>=16)throw Error(T('Maximum 16 panes'));const p={id:state.next++,kind,linked:true,selection:clone(selection),options:{},filters:{},sort:'',descending:false,offset:0,selected:[],columns:kind==='devices'?['attempt','part','wafer','x','y','site','passed','hard_bin','soft_bin','latest','issue']:kind==='records'?['record','kind','run','attempt','site','offset']:['record','number','name','pattern','site','value','units','low','high','passed','flags'],statistics:false,layout:'stacked',legend:true,zoom:null};state.panes.push(p);mount(p);refreshPane(p).catch(fail);saveLocal();return p;}
function mount(p){const el=document.createElement('article');el.className='pane';el.dataset.pane=p.id;const head=document.createElement('div');head.className='pane-head';head.innerHTML=`<strong>${esc(p.title||T(labels[p.kind]))}</strong>`;
 const link=button('Link',()=>{p.linked=true;p.offset=0;mountAll();refreshPane(p).catch(fail);saveLocal();});link.classList.toggle('active',p.linked);head.append(link);
 const pin=button('Pin',()=>{p.selection=clone(state.selection);p.linked=false;mountAll();saveLocal();});pin.classList.toggle('active',!p.linked);head.append(pin,button('New',()=>{const n=addPane(p.kind,p.linked?state.selection:p.selection);n.options=clone(p.options);for(const key of['columns','filters','values','layout','legend','sigma','mapColor','rotation','xLabel','yLabel','axes'])if(p[key]!==undefined)n[key]=clone(p[key]);n.linked=p.linked;mountAll();refreshPane(n).catch(fail);}),button('Statistics',()=>{p.statistics=!p.statistics;refreshPane(p).catch(fail);}),button('Properties',()=>properties(p)),button('Image',()=>imageExport(p)),button('×',()=>{state.panes=state.panes.filter(a=>a.id!==p.id);el.remove();regroup();saveLocal();}));
 const meta=document.createElement('div');meta.className='pane-meta';const body=document.createElement('div');body.className='pane-body';const foot=document.createElement('div');foot.className='pane-foot';el.append(head,meta,body,foot);$('panes').append(el);p.element=el;if(p.height)el.style.height=p.height+'px';
}
function regroup(){const root=$('panes');for(const p of state.panes)root.append(p.element);root.querySelectorAll('.tab-group').forEach(n=>n.remove());const groups=new Map;for(const p of state.panes)if(p.group)(groups.get(p.group)||groups.set(p.group,[]).get(p.group)).push(p);for(const [name,panes]of groups){const wrap=document.createElement('div');wrap.className='tab-group';const tabs=document.createElement('div');tabs.className='group-tabs';wrap.append(tabs);const active=panes.find(p=>p.groupActive)||panes[0];for(const p of panes){p.element.hidden=p!==active;wrap.append(p.element);const tab=button(p.title||labels[p.kind],()=>{for(const other of panes){other.groupActive=other===p;other.element.hidden=other!==p;}saveLocal();});tab.setAttribute('role','tab');tabs.append(tab);}root.append(wrap);}for(const p of state.panes)if(!p.group)p.element.hidden=false;}
function mountAll(){for(const p of state.panes){const old=p.element;mount(p);if(old){p.element.querySelector('.pane-body').replaceWith(old.querySelector('.pane-body'));p.element.querySelector('.pane-meta').replaceWith(old.querySelector('.pane-meta'));p.element.querySelector('.pane-foot').replaceWith(old.querySelector('.pane-foot'));old.remove();}}regroup();}
async function refreshPane(p){const revision=(p.revision||0)+1;p.revision=revision;const q=paneQuery(p),table=['measurements','devices','records','timing'].includes(p.kind);if(p.kind==='ffc'){p.element.querySelector('.pane-body').innerHTML=`<div class="empty">${esc(T('FFC requires a documented first-failing-cycle mapping. CYCL_CNT is not assumed to be FFC.'))}</div>`;return;}p.element.querySelector('.pane-meta').textContent=T('Loading');
 const data=await api(table?'rows':'plot',p.kind==='timing'?{...q,table:'devices'}:q);if(p.revision!==revision)return;p.data=data;
 p.element.querySelector('.pane-meta').textContent=`${T('Population')}: ${T(q.population==='all'?'All attempts':q.population==='latest'?'Latest':'First')} · ${p.linked?T('Linked'):T('Pinned')} · ${T('Excluded')}: ${q.excluded_measurements.length} ${T('measurements')}, ${q.excluded_devices.length} ${T('devices')} · ${T('Included')}: ${data.included??'—'} / ${T('Excluded')}: ${data.excluded??'—'}`;
 if(table)renderTable(p,data,q);else if(p.statistics)renderStats(p,data);else renderPlot(p,data,q);saveLocal();
}
function renderTable(p,data,q){const body=p.element.querySelector('.pane-body'),foot=p.element.querySelector('.pane-foot');body.replaceChildren();foot.replaceChildren();const scroll=document.createElement('div');scroll.className='table-scroll';let columns=p.kind==='timing'?['attempt','part','site','duration','start']:p.columns;
 const scale=Math.max(1,data.total*24/2400000);const top=document.createElement('div');top.style.height=`${q.offset*24/scale}px`;scroll.append(top);const table=document.createElement('table'),thead=document.createElement('thead'),tr=document.createElement('tr');tr.innerHTML='<th style="width:25px"></th>';
 for(const key of columns){const th=document.createElement('th');th.textContent=T(headings[key]||key)+(p.sort===key?(p.descending?' ▼':' ▲'):'');th.style.width=(key==='name'||key==='pattern'?200:100)+'px';if(key===columns[0])th.className='frozen';th.onclick=()=>{if(p.sort!==key){p.sort=key;p.descending=false;}else if(!p.descending)p.descending=true;else{p.sort='';p.descending=false;}p.offset=0;refreshPane(p).catch(fail);};const menu=button('▾',e=>{e.stopPropagation();columnFilter(p,key).catch(fail);},'Column filter');menu.style.cssText='float:right;padding:0 3px';th.append(menu);tr.append(th);}thead.append(tr);const filter=document.createElement('tr');filter.className='filters';filter.innerHTML='<th></th>';
 for(const key of columns){const th=document.createElement('th'),input=document.createElement('input');input.value=p.filters[key]||'';input.placeholder='⌕';input.title=T('Contains text or =, !=, >, >=, <, <=');input.setAttribute('aria-label',`${T('Filter')} ${headings[key]||key}`);let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{p.filters[key]=input.value;p.offset=0;refreshPane(p).catch(fail);},350);};th.append(input);filter.append(th);}thead.append(filter);table.append(thead);const tbody=document.createElement('tbody');
 data.rows.forEach((r,index)=>{const tr=document.createElement('tr');tr.dataset.id=r.id;tr.tabIndex=0;tr.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();inspect(r.record).catch(fail);}if(e.key==='ArrowDown'){e.preventDefault();tr.nextElementSibling?.focus();}if(e.key==='ArrowUp'){e.preventDefault();tr.previousElementSibling?.focus();}};const excluded=(q.table==='devices'?q.excluded_devices:q.excluded_measurements).includes(r.id),alert=Object.keys(q.alerts).length&&matches(r,q.alerts);tr.classList.toggle('failed',r.passed===false);tr.classList.toggle('selected',p.selected.includes(r.id));tr.classList.toggle('excluded',excluded);const annotation=document.createElement('td');annotation.className='annotation';annotation.textContent=[r.passed===false?'✕':'',r.alarm?'⚠':'',excluded?'−':'',alert?'!':''].join('');annotation.title=[r.passed===false?T('Fail'):'',r.alarm?T('Alarm'):'',excluded?T('Excluded'):'',alert?T('Alert'):''].filter(Boolean).join(', ');tr.append(annotation);
 for(const key of columns){const td=document.createElement('td');td.textContent=['test_method','foreground_time','background_time'].includes(key)?T('Unavailable'):key==='start'?utc(r[key]):key==='passed'?r[key]==null?T('Unknown'):T(r[key]?'Pass':'Fail'):fmt(r[key]);td.title=fmt(r[key]);if(key===columns[0])td.className='frozen';tr.append(td);}
 tr.onclick=e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey)p.selected=[];if(e.shiftKey&&p.anchor!=null){for(const v of data.rows.slice(Math.min(p.anchor,index),Math.max(p.anchor,index)+1))if(!p.selected.includes(v.id))p.selected.push(v.id);}else{const n=p.selected.indexOf(r.id);if(n>=0)p.selected.splice(n,1);else p.selected.push(r.id);p.anchor=index;}tbody.querySelectorAll('tr').forEach(t=>t.classList.toggle('selected',p.selected.includes(Number(t.dataset.id))));};tr.ondblclick=()=>inspect(r.record).catch(fail);tr.oncontextmenu=e=>{e.preventDefault();if(!p.selected.includes(r.id))p.selected=[r.id];rowMenu(p,r);};tbody.append(tr);});table.append(tbody);scroll.append(table);const bottom=document.createElement('div');bottom.style.height=`${Math.max(0,data.total-q.offset-data.rows.length)*24/scale}px`;scroll.append(bottom);body.append(scroll);
 scroll.scrollTop=top.offsetHeight;let debounce;scroll.onscroll=()=>{clearTimeout(debounce);const desired=Math.floor(scroll.scrollTop*scale/24);if(Math.abs(desired-q.offset)>50)debounce=setTimeout(()=>{p.offset=Math.max(0,Math.min(data.total-1,desired));refreshPane(p).catch(fail);},100);};
 const ruler=document.createElement('div');ruler.className='ruler';for(const a of data.annotations||[]){const mark=document.createElement('button');mark.style.top=(a.index/Math.max(1,data.total)*100)+'%';mark.title=`${a.index+1}: ${T(a.alert?'Alert':a.alarm?'Alarm':'Fail')}`;mark.onclick=()=>{p.offset=a.index;refreshPane(p).catch(fail);};ruler.append(mark);}body.append(ruler);
 if(p.kind==='timing'&&data.timing_summary)foot.append(document.createTextNode(`PRR Σ=${data.timing_summary.sum_ms} ms · n=${data.timing_summary.count} · ${T('Missing')}: ${data.timing_summary.missing}`));const status=document.createElement('span');status.textContent=`${q.offset+1}–${q.offset+data.rows.length} / ${data.total} · ${T('Included')}: ${data.included??'—'}`;foot.append(button('Previous',()=>{p.offset=Math.max(0,p.offset-80);refreshPane(p).catch(fail);}),status,button('Next',()=>{p.offset=Math.min(Math.max(0,data.total-1),p.offset+80);refreshPane(p).catch(fail);}),button('Previous annotation',()=>annotation(-1)),button('Next annotation',()=>annotation(1)),button('Copy',()=>copyRows(p)),button('CSV',()=>exportRows(p,'csv')),button('JSON',()=>exportRows(p,'json')));
 const choose=document.createElement('select');choose.title=T('Annotation type');for(const v of['all','failure','alarm','exclusion','alert'])choose.add(new Option(T(v),v));choose.value=q.annotation;choose.onchange=()=>{p.options.annotation=choose.value;refreshPane(p).catch(fail);};foot.append(choose);if(data.annotation_count>2000)foot.append(document.createTextNode(T('Ruler previews 2000 marks; navigation covers all')));
 function annotation(dir){const target=dir>0?data.next_annotation:data.previous_annotation;if(target!=null){p.offset=target;refreshPane(p).catch(fail);}else fail(T('No further annotation in the indexed preview'));}
}
async function columnFilter(p,key){const data=await api('distinct',{query:paneQuery(p),field:key});const selected=p.values?.[key];const d=modal('Column filter',`<input id="value-search" placeholder="${esc(T('Search'))}"><div id="value-items" style="max-height:400px;overflow:auto">${data.values.map((v,i)=>`<label style="display:block" data-search="${esc(fmt(v.value).toLowerCase())}"><input type="checkbox" value="${i}" ${!selected||selected.some(s=>JSON.stringify(s)===JSON.stringify(v.value))?'checked':''}>${esc(fmt(v.value))} (${v.count})</label>`).join('')}</div><div id="value-actions"></div>`);d.querySelector('#value-search').oninput=e=>d.querySelectorAll('[data-search]').forEach(n=>n.hidden=!n.dataset.search.includes(e.target.value.toLowerCase()));const actions=d.querySelector('#value-actions');actions.append(button('Select all',()=>d.querySelectorAll('[type=checkbox]').forEach(n=>n.checked=true)),button('Clear',()=>d.querySelectorAll('[type=checkbox]').forEach(n=>n.checked=false)),button('Apply',()=>{p.values??={};p.values[key]=[...d.querySelectorAll('[type=checkbox]:checked')].map(n=>data.values[+n.value].value);if(p.values[key].length===data.values.length)delete p.values[key];p.offset=0;d.close();refreshPane(p).catch(fail);}));}
function rowMenu(p,r){const d=modal('Selection actions','<div id="actions" style="display:flex;gap:8px;flex-wrap:wrap"></div>');const actions=d.querySelector('#actions');for(const [label,fn]of [['Inspect record',()=>inspect(r.record)],['Show In',()=>{const rows=(p.data?.rows||[]).filter(r=>p.selected.includes(r.id));state.selection.attempts=[...new Set(rows.map(r=>r.attempt).filter(Boolean))];state.selection.tests=p.kind==='measurements'?[...new Set(rows.map(r=>r.test))]:[];showIn();}],['Include',()=>setExclusion(p,false)],['Exclude',()=>setExclusion(p,true)],['Analyze Selection',()=>analyzeSelection(p)],['Copy',()=>copyRows(p)]])actions.append(button(label,()=>{d.close();Promise.resolve(fn()).catch(fail);}));}
async function setExclusion(p,exclude){const key=p.kind==='devices'?'excluded_devices':'excluded_measurements';if(!['devices','measurements','timing'].includes(p.kind))throw Error(T('Select devices or measurements to exclude'));const current=new Set(state.q[key]);for(const id of p.selected)exclude?current.add(id):current.delete(id);state.q[key]=[...current];await refreshAll();}
async function analyzeSelection(p){const q=paneQuery(p),data=await api('data-export',q),selected=new Set(p.selected),key=p.kind==='devices'?'excluded_devices':'excluded_measurements',excluded=new Set(state.q[key]);for(const r of data.rows)selected.has(r.id)?excluded.delete(r.id):excluded.add(r.id);state.q[key]=[...excluded];await refreshAll();}
async function copyRows(p){const rows=(p.data?.rows||[]).filter(r=>p.selected.includes(r.id));await navigator.clipboard.writeText([p.columns.join('\t'),...rows.map(r=>p.columns.map(k=>fmt(r[k]).replace(/[\t\r\n]/g,' ')).join('\t'))].join('\n'));}
async function exportRows(p,type){const data=await api('data-export',paneQuery(p));if(type==='json')download('viewer-evidence.json',JSON.stringify(data,null,2));else{const cell=v=>'"'+fmt(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';download('viewer-values.csv',[p.columns.map(cell).join(','),...data.rows.map(r=>p.columns.map(k=>cell(r[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8');}}
async function inspect(id){const result=await api('inspect',{id}),e=result.evidence;const d=modal('Record evidence',`<p>${esc(e.kind)} · ${T('Record')} ${e.id} · ${T('Offset')} ${e.offset} · ${T('Attempt')} ${e.attempt||'[unassigned]'}</p><table><thead><tr><th>Field</th><th>${esc(T('Raw value'))}</th><th>${esc(T('Effective value'))}</th><th>${esc(T('Origin'))}</th></tr></thead><tbody>${e.fields.map(f=>{const time=['SETUP_T','START_T','FINISH_T','END_T','MOD_TIM'].includes(f.name);const raw=numeric(f.raw),effective=numeric(f.effective);return`<tr><td title="${esc(raw==null?'[null]':time?utc(raw):fmt(raw))}">${esc(f.name)} <small>${esc(f.kind)}</small></td><td>${esc(fmt(raw))}${time&&raw!=null?'<br>'+esc(utc(raw)):''}</td><td>${esc(fmt(effective))}</td><td>${esc(f.origin)} ${esc(f.inherited_from||'')}<br>${esc(f.presence)} ${esc(f.issues?.join('; ')||'')}</td></tr>`;}).join('')}</tbody></table>${result.hex?`<details><summary>Hex</summary><pre>${esc(result.hex)}</pre></details>`:''}`);return d;}
function renderStats(p,data){const body=p.element.querySelector('.pane-body');if(data.series){const cols=['count','invalid','missing','nonfinite','not_numeric','mean','min','max','sigma','ppk','quantiles'];body.innerHTML=`<table><thead><tr><th>${esc(T('Series'))}</th>${cols.map(c=>`<th>${esc(T(c==='ppk'?'Ppk (overall sigma)':c))}</th>`).join('')}</tr></thead><tbody>${Object.entries(data.series).map(([k,v])=>`<tr><td>${esc(labelSeries(k))}</td>${cols.map(c=>`<td>${esc(fmt(v[c]))}</td>`).join('')}</tr>`).join('')}</tbody></table><p>${esc(T('Exact statistics'))} · ${esc(T('Sample standard deviation; linearly interpolated quantiles'))}</p>`;}else body.innerHTML=`<pre class="info">${esc(JSON.stringify(data,null,2))}</pre>`;p.element.querySelector('.pane-foot').replaceChildren();}
function labelSeries(key){try{const v=JSON.parse(key),t=JSON.parse(v[0]);return`${t[1]??''} ${t[2]}${t[3]==null?'':` [${t[3]}]`} · ${v[1]} ${v[2]}`;}catch{return key;}}
function renderPlot(p,data,q){
 const body=p.element.querySelector('.pane-body'),foot=p.element.querySelector('.pane-foot');body.replaceChildren();foot.replaceChildren();if(data.unavailable){body.textContent=data.unavailable;return;}const unitGroups=new Map;for(const [k,v]of Object.entries(data.series||{}))if(v.count){(unitGroups.get(v.units)||unitGroups.set(v.units,{}).get(v.units))[k]=v;}if(unitGroups.size>1){for(const [unit,series]of unitGroups){const section=document.createElement('section');section.innerHTML=`<strong>${esc(T('Units'))}: ${esc(unit||'[null]')}</strong><div class="pane-body"></div><div class="pane-foot"></div>`;body.append(section);renderPlot({...p,element:section},{...data,series},q);}return;}const W=760,H=300,L=65,R=30,TOP=25,BOTTOM=50,iw=W-L-R,ih=H-TOP-BOTTOM;
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('chart');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',T(labels[p.kind]));body.append(svg);
 function node(tag,attrs,text){const n=document.createElementNS(svg.namespaceURI,tag);for(const [k,v]of Object.entries(attrs||{}))n.setAttribute(k,v);if(text!=null)n.textContent=text;svg.append(n);return n;}
 function hit(n,r){if(!r)return;n.classList.add('hit');n.setAttribute('tabindex','0');const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${r.name||''} · ${T('Attempt')} ${r.attempt??''} · ${T('Value')} ${fmt(r.value??r.y)} · ${T('Record')} ${r.record??''}`;n.append(title);const click=()=>{if(r.attempt){state.selection.attempts=[r.attempt];for(const other of state.panes)if(other.linked&&other.kind==='measurements'){other.offset=0;refreshPane(other).catch(fail);}}if(r.record)inspect(r.record).catch(fail);};n.onclick=click;n.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();click();}};}
 const entries=Object.entries(data.series||{}),series=entries.map(([key,s],i)=>({key,label:labelSeries(key),s,color:colors[i%colors.length]}));let xmin=0,xmax=1,ymin=0,ymax=1,xlabel=T('Value'),ylabel=T('Count'),marks=[];
 if(p.kind==='pareto'){
  const modes=data.modes||[],start=p.modeOffset||0,shown=modes.slice(start,start+25),max=Math.max(1,...shown.map(v=>v.count));xmin=0;xmax=max;ymin=0;ymax=Math.max(1,shown.length);xlabel=T('Count');ylabel='';
  const sx=x=>L+x/max*iw,bh=ih/Math.max(1,shown.length),groups=[...new Set(shown.flatMap(v=>Object.keys(v.groups)))];
  shown.forEach((m,i)=>{node('text',{x:L-5,y:TOP+(i+.65)*bh,'text-anchor':'end','font-size':10},m.label.length>28?m.label.slice(0,26)+'…':m.label);let offset=0;Object.entries(m.groups).forEach(([group,n],j)=>{const y=TOP+i*bh+(p.layout==='grouped'?j*bh/Object.keys(m.groups).length:0),height=p.layout==='grouped'?bh/Object.keys(m.groups).length:bh;const rect=node('rect',{x:sx(p.layout==='grouped'?0:offset),y:y+1,width:sx(n)-L,height:Math.max(1,height-2),fill:colors[groups.indexOf(group)%colors.length]});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${m.label} · ${group}: ${n}`;rect.append(title);rect.onclick=()=>{state.selection.hard_bins=q.level==='hard_bin'&&m.label!=='[null]'?[Number(m.label)]:[];state.selection.soft_bins=q.level==='soft_bin'&&m.label!=='[null]'?[Number(m.label)]:[];if(q.level==='test'){const mtest=m.label.match(/^(PTR|MPR|FTR) (\d+) (.*)$/s);if(mtest)state.selection.tests=[JSON.stringify([mtest[1],Number(mtest[2]),mtest[3],null])];const log=state.panes.find(p=>p.kind==='measurements')||addPane('measurements');log.filters.passed='=false';refreshAll().catch(fail);}else if(q.level==='pattern'){state.selection.tests=[];const log=state.panes.find(p=>p.kind==='measurements')||addPane('measurements');log.filters.pattern='='+m.label;log.filters.passed='=false';refreshPane(log).catch(fail);}else refreshAll().catch(fail);};offset+=n;});});
  foot.append(button('Previous',()=>{p.modeOffset=Math.max(0,start-25);renderPlot(p,data,q);}),document.createTextNode(`${start+1}–${start+shown.length} / ${modes.length}`),button('Next',()=>{p.modeOffset=Math.min(Math.max(0,modes.length-1),start+25);renderPlot(p,data,q);}),button(p.layout==='stacked'?'Side by side':'Stacked',()=>{p.layout=p.layout==='stacked'?'grouped':'stacked';renderPlot(p,data,q);}));
 }else if(['binmap','paramap'].includes(p.kind)){
  const cells=data.cells||[];if(!cells.length){body.innerHTML=`<div class="empty">${esc(T('No mapped devices'))}</div>`;return;}
  const available=[...new Set(cells.map(r=>r.wafer))],wafers=[...(p.waferOrder||[]).filter(w=>available.includes(w)),...available.filter(w=>!(p.waferOrder||[]).includes(w))];const grouped=new Map;for(const r of cells){const key=`${r.x},${r.y}`;(grouped.get(key)||grouped.set(key,[]).get(key)).push(r);}
  const rot=p.rotation||0,transform=(x,y)=>rot===90?[-y,x]:rot===180?[-x,-y]:rot===270?[y,-x]:[x,y];const coordinates=cells.map(r=>transform(r.x,p.flipY?-r.y:r.y)),xs=coordinates.map(v=>v[0]),ys=coordinates.map(v=>v[1]);xmin=Math.min(...xs)-.5;xmax=Math.max(...xs)+.5;ymin=Math.min(...ys)-.5;ymax=Math.max(...ys)+.5;xlabel='X';ylabel='Y';
  const vals=cells.filter(r=>r.value!=null).map(r=>r.value),min=Math.min(...vals),max=Math.max(...vals);let incomplete=0;
  for(const rs of grouped.values()){const r=rs[0],byWafer=wafers.map(w=>rs.filter(r=>r.wafer===w)),verdicts=byWafer.map(a=>!a.length||a.some(r=>r.passed==null)?null:a.every(r=>r.passed));const coverage=byWafer.filter(a=>a.length).length,unknown=verdicts.some(v=>v==null);if(coverage<wafers.length)incomplete++;
   const vs=rs.filter(r=>r.value!=null).map(r=>r.value),v=!vs.length?null:q.statistic==='min'?Math.min(...vs):q.statistic==='max'?Math.max(...vs):vs.reduce((a,b)=>a+b,0)/vs.length;
   const ratio=verdicts.filter(v=>v===true).length/wafers.length;let color=unknown?'#a1a8af':wafers.length===2?(verdicts[0]?verdicts[1]?'#398c60':'#9767b8':verdicts[1]?'#ddb32d':'#cb6549'):`hsl(${ratio*120} 45% 44%)`;
   if(p.kind==='paramap')color=v==null?'#a1a8af':`hsl(${240-(max===min?.5:(v-min)/(max-min))*240} 60% 50%)`;
   else if(p.mapColor&&p.mapColor!=='verdict'){const bins=[...new Set(rs.map(r=>r[p.mapColor]))];color=bins.length===1&&bins[0]!=null?colors[bins[0]%colors.length]:'#a1a8af';}
   const [x,y]=transform(r.x,p.flipY?-r.y:r.y),n=node('rect',{x:L+(x-.45-xmin)/(xmax-xmin)*iw,y:TOP+(ymax-y-.45)/(ymax-ymin)*ih,width:Math.max(2,iw/(xmax-xmin)*.9),height:Math.max(2,ih/(ymax-ymin)*.9),fill:color,stroke:'var(--ui-surface)','stroke-width':.5});
   hit(n,{...r,value:v});n.querySelector('title').textContent=`X=${r.x}, Y=${r.y} · ${T('Wafers')}: ${coverage}/${wafers.length} · ${q.statistic}=${fmt(v)} · `+wafers.map((w,i)=>`${w}: ${verdicts[i]==null?'?':verdicts[i]?'P':'F'}`).join(' | ');
   n.onclick=()=>{state.selection.attempts=rs.map(r=>r.attempt);const pane=state.panes.find(p=>p.kind==='devices')||addPane('devices');refreshPane(pane).catch(fail);for(const log of state.panes.filter(p=>p.linked&&p.kind==='measurements'))refreshPane(log).catch(fail);};
  }
  const legend=document.createElement('div');legend.className='legend';legend.textContent=p.kind==='paramap'?`${q.statistic}: ${fmt(min)} – ${fmt(max)} · ${T('Missing values remain unmeasured')}`:wafers.length===2?'P/P green · P/F purple · F/P amber · F/F red · unknown/missing grey':`P green · F red · ${T('Unknown')} grey · ${p.mapColor||'verdict'}`;body.append(legend);
  foot.append(document.createTextNode(`${T('Wafers')}: ${wafers.join(' → ')} · ${T('Missing coordinates')}: ${data.missing_coordinates} · ${T('Incomplete coverage')}: ${incomplete}`),button('Rotate',()=>{p.rotation=(rot+90)%360;renderPlot(p,data,q);}),button('Flip Y',()=>{p.flipY=!p.flipY;renderPlot(p,data,q);}),button('Reverse wafer order',()=>{p.waferOrder=[...wafers].reverse();renderPlot(p,data,q);}));

 }else{
  const all=series.flatMap(v=>v.s.points||[]),values=series.flatMap(v=>v.s.count?[v.s.min,v.s.max]:[]);xmin=values.length?Math.min(...values):0;xmax=values.length?Math.max(...values):1;
  if(p.kind==='scatter'&&data.points){xmin=Math.min(...data.points.map(p=>p.x));xmax=Math.max(...data.points.map(p=>p.x));ymin=Math.min(...data.points.map(p=>p.y));ymax=Math.max(...data.points.map(p=>p.y));xlabel='X';ylabel='Y';marks=data.points.map(r=>({x:r.x,y:r.y,r,color:colors[r.site%colors.length]}));foot.append(document.createTextNode(`r=${fmt(data.correlation)} · ${T('Pairs')}: ${data.count} · ${T('Unpaired')}: ${data.unpaired}`));}
  else if(['box','range'].includes(p.kind)||p.kind==='scatter'){xmin=-.5;xmax=Math.max(.5,series.length-.5);ymin=values.length?Math.min(...values):0;ymax=values.length?Math.max(...values):1;xlabel=T('Test');ylabel=T('Value');}
  else if(p.kind==='trend'){xmin=all.length?Math.min(...all.map(r=>r.record)):0;xmax=all.length?Math.max(...all.map(r=>r.record)):1;ymin=values.length?Math.min(...values):0;ymax=values.length?Math.max(...values):1;xlabel=T('Record sequence');ylabel=T('Value');marks=series.flatMap(v=>v.s.points.map(r=>({x:r.record,y:r.value,r,color:v.color})));}
  else if(p.kind==='probability'){ymin=0;ymax=100;ylabel=T('Probability (%)');for(const v of series)for(const r of v.s.cdf||[])marks.push({x:r.value,y:r.probability,r,color:v.color});}
  else {xmin=Math.min(...series.filter(v=>v.s.count).map(v=>v.s.hist_min));xmax=Math.max(...series.filter(v=>v.s.count).map(v=>v.s.hist_max));ymin=0;ymax=p.layout==='grouped'?Math.max(1,...series.flatMap(v=>v.s.histogram||[])):Math.max(1,...Array.from({length:q.bins},(_,i)=>series.reduce((n,v)=>n+(v.s.histogram[i]||0),0)));}
  if(p.kind==='histogram'){const ext=series.flatMap(v=>[v.s.low,v.s.high,...(p.sigma&&v.s.sigma?[v.s.mean-3*v.s.sigma,v.s.mean+3*v.s.sigma]:[])]).filter(v=>v!=null);xmin=Math.min(xmin,...ext);xmax=Math.max(xmax,...ext);}if(p.kind==='trend'){const ext=all.flatMap(r=>[r.low,r.high]).filter(v=>v!=null);ymin=Math.min(ymin,...ext);ymax=Math.max(ymax,...ext);}
  if(p.axes){xmin=p.axes.xmin??xmin;xmax=p.axes.xmax??xmax;ymin=p.axes.ymin??ymin;ymax=p.axes.ymax??ymax;}if(xmin>xmax||ymin>ymax){body.textContent=T('Invalid axis bounds');return;}
  if(xmin===xmax){xmin-=.5;xmax+=.5;}if(ymin===ymax){ymin-=.5;ymax+=.5;}if(![xmin,xmax,ymin,ymax].every(Number.isFinite)){body.innerHTML=`<div class="empty">${esc(T('No valid numeric data'))}</div>`;return;}
  if(p.zoom){[xmin,xmax,ymin,ymax]=p.zoom;}const sx=x=>L+(x-xmin)/(xmax-xmin)*iw,sy=y=>TOP+(ymax-y)/(ymax-ymin)*ih;
  if(p.kind==='histogram'){
   const accumulated=Array(q.bins).fill(0);for(const [si,v]of series.entries()){const s=v.s;if(!s.count)continue;const width=(s.hist_max-s.hist_min)/q.bins;for(let i=0;i<s.histogram.length;i++){const x=s.hist_min+i*width,w=Math.max(1,sx(x+width)-sx(x)),n=s.histogram[i],bw=p.layout==='grouped'?w/series.length:w;node('rect',{x:sx(x)+(p.layout==='grouped'?si*bw:0),y:sy(n+(p.layout==='grouped'?0:accumulated[i])),width:Math.max(1,bw-1),height:sy(0)-sy(n),fill:v.color,opacity:.85});accumulated[i]+=n;}if(!s.variable_limits)for(const lim of[s.low,s.high])if(lim!=null)node('line',{x1:sx(lim),x2:sx(lim),y1:TOP,y2:H-BOTTOM,stroke:'#bd4937','stroke-dasharray':'5 3'});node('line',{x1:sx(s.mean),x2:sx(s.mean),y1:TOP,y2:H-BOTTOM,stroke:v.color,'stroke-width':2});if(p.sigma&&s.sigma)for(const k of[-3,-2,2,3])node('line',{x1:sx(s.mean+k*s.sigma),x2:sx(s.mean+k*s.sigma),y1:TOP,y2:H-BOTTOM,stroke:v.color,'stroke-dasharray':'2 4'});}
   const total=series.reduce((n,v)=>n+v.s.count,0);for(let i=0;i<=5;i++)node('text',{x:W-R+3,y:TOP+i/5*ih+3,'font-size':9},`${fmt((ymax-i/5*ymax)/Math.max(1,total)*100)}%`);for(const bins of[10,20,30])foot.append(button(String(bins),()=>{p.options.bins=bins;refreshPane(p).catch(fail);}));
   foot.append(button('Half bins',()=>{p.options.bins=Math.max(1,Math.floor(q.bins/2));refreshPane(p).catch(fail);}),document.createTextNode(`${q.bins} ${T('bins')}`),button('Double bins',()=>{p.options.bins=Math.min(1024,q.bins*2);refreshPane(p).catch(fail);}));
  }else if(['box','range'].includes(p.kind)||p.kind==='scatter'&&!data.points){series.forEach((v,i)=>{const s=v.s;if(!s.count)return;const x=sx(i),a=p.kind==='box'?s.quantiles:[s.min,s.mean,s.mean,s.mean,s.max];node('line',{x1:x,x2:x,y1:sy(a[0]),y2:sy(a[4]),stroke:v.color,'stroke-width':2});for(const y of[a[0],a[4]])node('line',{x1:x-10,x2:x+10,y1:sy(y),y2:sy(y),stroke:v.color});if(p.kind==='box'){node('rect',{x:x-16,y:sy(a[3]),width:32,height:Math.max(1,sy(a[1])-sy(a[3])),fill:v.color,opacity:.4});node('line',{x1:x-16,x2:x+16,y1:sy(a[2]),y2:sy(a[2]),stroke:v.color,'stroke-width':2});for(const r of s.points.filter(r=>r.value<a[0]||r.value>a[4]))hit(node('circle',{cx:x,cy:sy(r.value),r:2,fill:v.color}),r);}else node('circle',{cx:x,cy:sy(s.mean),r:4,fill:v.color});});}
  else for(const m of marks)if(m.x>=xmin&&m.x<=xmax&&m.y>=ymin&&m.y<=ymax)hit(node('circle',{cx:sx(m.x),cy:sy(m.y),r:2.7,fill:m.color}),m.r);
  if(['range','scatter'].includes(p.kind)&&q.tests.length===2)foot.append(button(p.kind==='range'?'Scatter':'Range',()=>{p.kind=p.kind==='range'?'scatter':'range';mountAll();refreshPane(p).catch(fail);}));
  if(p.kind==='trend')for(const v of series)for(const key of['low','high']){const pts=v.s.points.filter(r=>r[key]!=null).map(r=>`${sx(r.record)},${sy(r[key])}`).join(' ');node('polyline',{points:pts,fill:'none',stroke:'#b94b39','stroke-dasharray':'4 3'});}
  let down=null,rect=null;svg.onpointerdown=e=>{if(e.target.classList.contains('hit'))return;const box=svg.getBoundingClientRect();down=[(e.clientX-box.left)/box.width*W,(e.clientY-box.top)/box.height*H];svg.setPointerCapture(e.pointerId);rect=node('rect',{x:down[0],y:down[1],width:0,height:0,fill:'#287bb522',stroke:'#287bb5'});};svg.onpointermove=e=>{if(!down)return;const b=svg.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*W,y=(e.clientY-b.top)/b.height*H;rect.setAttribute('x',Math.min(x,down[0]));rect.setAttribute('y',Math.min(y,down[1]));rect.setAttribute('width',Math.abs(x-down[0]));rect.setAttribute('height',Math.abs(y-down[1]));};svg.onpointerup=()=>{if(!down)return;const x=+rect.getAttribute('x'),y=+rect.getAttribute('y'),w=+rect.getAttribute('width'),h=+rect.getAttribute('height');if(w>8&&h>8)p.zoom=[xmin+(x-L)/iw*(xmax-xmin),xmin+(x+w-L)/iw*(xmax-xmin),ymax-(y+h-TOP)/ih*(ymax-ymin),ymax-(y-TOP)/ih*(ymax-ymin)];down=null;renderPlot(p,data,q);};
 }
 svg.ondblclick=()=>{p.zoom=null;renderPlot(p,data,q);};
 node('line',{x1:L,y1:H-BOTTOM,x2:W-R,y2:H-BOTTOM,stroke:'var(--ui-muted)'});node('line',{x1:L,y1:TOP,x2:L,y2:H-BOTTOM,stroke:'var(--ui-muted)'});
 for(let i=0;i<=5;i++){const x=L+i/5*iw,y=TOP+i/5*ih;node('text',{x,y:H-BOTTOM+17,'text-anchor':'middle','font-size':10},fmt(xmin+i/5*(xmax-xmin)));if(p.kind!=='pareto')node('text',{x:L-6,y:y+3,'text-anchor':'end','font-size':10},fmt(ymax-i/5*(ymax-ymin)));}
 node('text',{x:L+iw/2,y:H-8,'text-anchor':'middle','font-size':12},p.xLabel||xlabel);node('text',{x:12,y:15,'font-size':11},p.yLabel||ylabel);
 if(p.legend&&series.length){const legend=document.createElement('div');legend.className='legend';legend.innerHTML=series.map(v=>`<span><i style="background:${v.color}"></i>${esc(v.label)} · n=${v.s.count} · σ=${esc(fmt(v.s.sigma))}</span>`).join('');body.append(legend);}
 const sampled=data.sampled||series.some(v=>v.s.sampled);if(sampled)foot.append(document.createTextNode(T('Plot points reduced; statistics use all selected values')));if(!data.modes&&!data.cells&&!series.length&&!data.points)foot.append(document.createTextNode(T('No valid numeric data')));
}
function properties(p){if(boot.scope==='summary'){fail(T('Summary snapshot settings are fixed'));return;}const q=paneQuery(p),d=modal('Properties',`<div class="properties"><label>${esc(T('Columns'))}</label><div>${Object.entries(headings).map(([k,v])=>`<label class="inline"><input type="checkbox" name="column" value="${k}" ${p.columns.includes(k)?'checked':''}>${esc(T(v))}</label>`).join(' ')}</div><label>${esc(T('Tab group'))}</label><input id="prop-group" placeholder="A / B" value="${esc(p.group||'')}"><label>${esc(T('Title'))}</label><input id="prop-title" value="${esc(p.title||'')}"><label>${esc(T('X label'))}</label><input id="prop-xlabel" value="${esc(p.xLabel||'')}"><label>${esc(T('Y label'))}</label><input id="prop-ylabel" value="${esc(p.yLabel||'')}"><label>${esc(T('Axis bounds'))}</label><div>${['xmin','xmax','ymin','ymax'].map(k=>`<input id="prop-${k}" placeholder="${k}" type="number" value="${p.axes?.[k]??''}">`).join(' ')}</div><label>${esc(T('Legend'))}</label><input id="prop-legend" type="checkbox" ${p.legend?'checked':''}><label>${esc(T('Map color'))}</label><select id="prop-map-color">${['verdict','hard_bin','soft_bin'].map(v=>`<option ${v===(p.mapColor||'verdict')?'selected':''}>${v}</option>`).join('')}</select><label>${esc(T('Sites'))}</label><input id="prop-sites" placeholder="1,2,3" value="${q.sites.join(',')}"><label>${esc(T('Bins'))}</label><input id="prop-bins" type="number" min="1" max="1024" value="${q.bins}"><label>${esc(T('Whisker percentiles'))}</label><div><input id="prop-low" type="number" value="${q.low_whisker}" min="0" max="100"> <input id="prop-high" type="number" value="${q.high_whisker}" min="0" max="100"></div><label>${esc(T('Color by'))}</label><select id="prop-color">${['site','wafer','lot','none'].map(v=>`<option ${v===q.color?'selected':''}>${v}</option>`).join('')}</select><label>${esc(T('Pareto level'))}</label><select id="prop-level">${['hard_bin','soft_bin','test','pattern'].map(v=>`<option ${v===q.level?'selected':''}>${v}</option>`).join('')}</select><label>${esc(T('Show passing bins'))}</label><input id="prop-pass" type="checkbox" ${q.show_pass?'checked':''}><label>${esc(T('Layout'))}</label><select id="prop-layout"><option value="stacked">${esc(T('Stacked'))}</option><option value="grouped" ${p.layout==='grouped'?'selected':''}>${esc(T('Side by side'))}</option></select><label>${esc(T('Mean / sigma lines'))}</label><input id="prop-sigma" type="checkbox" ${p.sigma?'checked':''}><label>${esc(T('Map statistic'))}</label><select id="prop-stat">${['mean','min','max'].map(v=>`<option ${v===q.statistic?'selected':''}>${v}</option>`).join('')}</select><label>${esc(T('Alert field'))}</label><select id="prop-alert-key"><option value="">—</option>${Object.entries(headings).map(([k,v])=>`<option value="${k}">${esc(T(v))}</option>`).join('')}</select><label>${esc(T('Alert condition'))}</label><input id="prop-alert-value" placeholder=">1.5"><button id="prop-apply">${esc(T('Apply'))}</button></div>`);
 d.querySelector('#prop-apply').onclick=()=>{p.group=d.querySelector('#prop-group').value.trim();p.title=d.querySelector('#prop-title').value;p.xLabel=d.querySelector('#prop-xlabel').value;p.yLabel=d.querySelector('#prop-ylabel').value;p.axes=Object.fromEntries(['xmin','xmax','ymin','ymax'].map(k=>[k,d.querySelector('#prop-'+k).value===''?null:Number(d.querySelector('#prop-'+k).value)]));p.legend=d.querySelector('#prop-legend').checked;p.mapColor=d.querySelector('#prop-map-color').value;p.columns=[...d.querySelectorAll('[name=column]:checked')].map(n=>n.value);if(!p.columns.length)p.columns=['record'];p.options={...p.options,sites:d.querySelector('#prop-sites').value.split(',').filter(Boolean).map(Number),bins:+d.querySelector('#prop-bins').value,low_whisker:+d.querySelector('#prop-low').value,high_whisker:+d.querySelector('#prop-high').value,color:d.querySelector('#prop-color').value,level:d.querySelector('#prop-level').value,show_pass:d.querySelector('#prop-pass').checked,statistic:d.querySelector('#prop-stat').value};p.layout=d.querySelector('#prop-layout').value;p.sigma=d.querySelector('#prop-sigma').checked;const key=d.querySelector('#prop-alert-key').value;if(key)state.q.alerts[key]=d.querySelector('#prop-alert-value').value;d.close();mountAll();refreshPane(p).catch(fail);};}
function imageExport(p){const svg=p.element.querySelector('svg');if(!svg){fail(T('Open a plot before exporting an image'));return;}const plots=[...p.element.querySelectorAll('svg.chart')],copy=document.createElementNS(svg.namespaceURI,'svg');copy.setAttribute('xmlns','http://www.w3.org/2000/svg');plots.forEach((plot,i)=>{const n=plot.cloneNode(true);n.setAttribute('x','0');n.setAttribute('y',String(i*300));n.setAttribute('width','760');n.setAttribute('height','300');copy.append(n);});const legend=Object.entries(p.data?.series||{}).filter(([,s])=>plots.length===1||s.count),plotHeight=plots.length*300;const height=plotHeight+30+legend.length*15;copy.setAttribute('viewBox',`0 0 760 ${height}`);const caption=document.createElementNS(svg.namespaceURI,'text');caption.setAttribute('x','15');caption.setAttribute('y',String(plotHeight+18));caption.setAttribute('font-size','11');caption.textContent=`${p.title||T(labels[p.kind])} · ${T('Population')}: ${paneQuery(p).population}`;copy.append(caption);const unitColors=new Map;legend.forEach(([key,series],i)=>{const ci=plots.length===1?i:(unitColors.get(series.units)||0);unitColors.set(series.units,ci+1);const t=document.createElementNS(svg.namespaceURI,'text');const swatch=document.createElementNS(svg.namespaceURI,'rect');swatch.setAttribute('x','15');swatch.setAttribute('y',String(plotHeight+27+i*15));swatch.setAttribute('width','8');swatch.setAttribute('height','8');swatch.setAttribute('fill',colors[ci%colors.length]);copy.append(swatch);t.setAttribute('x','30');t.setAttribute('y',String(plotHeight+35+i*15));t.setAttribute('font-size','10');t.textContent=labelSeries(key);copy.append(t);});copy.querySelectorAll('text').forEach(n=>n.setAttribute('fill',window.ReportUI.color('ink')));let xml=new XMLSerializer().serializeToString(copy);xml=xml.replace(/var\(--ui-muted\)/g,window.ReportUI.color('muted')).replace(/var\(--ui-surface\)/g,window.ReportUI.color('surface'));const d=modal('Image','<div id="image-actions"></div>');d.querySelector('#image-actions').append(button('SVG',()=>{download('viewer-plot.svg',xml,'image/svg+xml');d.close();}),button('PNG',()=>{const image=new Image,url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));image.onload=()=>{const c=document.createElement('canvas');c.width=1520;c.height=height*2;const ctx=c.getContext('2d');ctx.fillStyle=window.ReportUI.color('surface');ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(image,0,0,c.width,c.height);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='viewer-plot.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);});URL.revokeObjectURL(url);};image.src=url;d.close();}));}
function showIn(){const d=modal('Show In','<div id="view-list" style="display:flex;gap:8px;flex-wrap:wrap"></div>');for(const kind of['measurements','devices','records','histogram','box','probability','trend','scatter','range','pareto','binmap','paramap','timing','ffc'])d.querySelector('#view-list').append(button(labels[kind],()=>{d.close();addPane(kind);}));}
async function navigation(){const revision=++state.revision;const nav=$('nav-tabs');nav.replaceChildren();for(const kind of['information','tests','devices','wafers','hard_bin','soft_bin']){const b=button(labels[kind],()=>{state.nav=kind;state.navOffset=0;state.navSelected=[];navigation().catch(fail);});b.classList.toggle('active',state.nav===kind);nav.append(b);}if(state.nav==='information'){$('nav-content').innerHTML=`<div class="info"><b>${esc(T('Source'))}</b>\n${esc(boot.manifest.source)}\n\nSHA-256\n${esc(boot.manifest.source_hash)}\n\n${esc(T('Records'))}: ${boot.manifest.records}\n${esc(T('Devices'))}: ${boot.manifest.attempts}\n${esc(T('Measurements'))}: ${boot.manifest.measurements}\n${esc(T('Profile'))}: ${esc(boot.flow||T('Not selected'))}\n\n${esc(JSON.stringify(boot.manifest.inventory,null,2))}\n\n${esc(T('Validation'))}\n${esc(JSON.stringify(boot.validation,null,2))}\n\n${esc(T('Single-file snapshot. No manufacturing flow completeness is inferred.'))}</div>`;$('nav-pages').replaceChildren();return;}
 const data=await api('rows',{...clone(state.q),table:state.nav,offset:state.navOffset,limit:100,tests:[],attempts:[],filters:{},values:{},search:$('nav-search').value,sort:'',descending:false});if(revision!==state.revision)return;const rows=data.rows;const table=document.createElement('table');const cols=state.nav==='devices'?['attempt','part','site','passed','latest']:['name','count','fail'];table.innerHTML=`<thead><tr>${cols.map(k=>`<th>${esc(T(headings[k]||k))}</th>`).join('')}</tr></thead>`;const tbody=document.createElement('tbody');rows.forEach((r,i)=>{const tr=document.createElement('tr');tr.innerHTML=cols.map(k=>`<td title="${esc(fmt(r[k]))}">${esc(fmt(r[k]))}</td>`).join('');const key=r.key??r.attempt;tr.classList.toggle('selected',state.navSelected.includes(key));tr.onclick=e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey)state.navSelected=[];if(e.shiftKey&&state.navAnchor!=null){for(const a of rows.slice(Math.min(i,state.navAnchor),Math.max(i,state.navAnchor)+1))if(!state.navSelected.includes(a.key??a.attempt))state.navSelected.push(a.key??a.attempt);}else if(state.navSelected.includes(key))state.navSelected=state.navSelected.filter(k=>k!==key);else state.navSelected.push(key);state.navAnchor=i;state.selection={tests:[],attempts:[],hard_bins:[],soft_bins:[]};if(state.nav==='tests')state.selection.tests=[...state.navSelected];if(state.nav==='devices')state.selection.attempts=[...state.navSelected];if(state.nav==='wafers'){state.q.wafer=key==='[null]'?null:key;$('wafer').value=state.q.wafer||'';}if(state.nav==='hard_bin')state.selection.hard_bins=state.navSelected.filter(k=>k!=='[null]').map(Number);if(state.nav==='soft_bin')state.selection.soft_bins=state.navSelected.filter(k=>k!=='[null]').map(Number);for(const p of state.panes)if(p.linked){p.offset=0;refreshPane(p).catch(fail);}navigation().catch(fail);};tbody.append(tr);});table.append(tbody);$('nav-content').replaceChildren(table);$('nav-pages').replaceChildren(button('Previous',()=>{state.navOffset=Math.max(0,state.navOffset-100);navigation().catch(fail);}),document.createTextNode(`${state.navOffset+1}–${state.navOffset+data.rows.length}/${data.total}`),button('Next',()=>{state.navOffset=Math.min(Math.max(0,data.total-1),state.navOffset+100);navigation().catch(fail);}));}
async function refreshAll(){clearError();await navigation();for(const p of state.panes){p.offset=0;await refreshPane(p);}}
function session(){return{version:1,source_hash:boot.manifest.source_hash,q:state.q,selection:state.selection,nav:state.nav,navWidth:$('navigation').getBoundingClientRect().width,panes:state.panes.map(({element,data,revision,...p})=>({...p,height:element.getBoundingClientRect().height||p.height}))};}
function saveLocal(){try{localStorage.setItem('zstdf-viewer-'+boot.manifest.source_hash,JSON.stringify(session()));}catch{}}
function restore(s){if(s.source_hash!==boot.manifest.source_hash)throw Error(T('Session source hash does not match'));if(s.version!==1||!Array.isArray(s.panes)||s.panes.length>16)throw Error(T('Unsupported session'));state.q={...clone(defaults),...s.q};state.selection=s.selection;state.nav=s.nav;if(s.navWidth)$('navigation').style.width=Math.max(220,Math.min(650,s.navWidth))+'px';state.panes=[];$('panes').replaceChildren();for(const p of s.panes){p.element=null;state.panes.push(p);mount(p);}regroup();state.next=Math.max(0,...state.panes.map(p=>p.id))+1;$('population').value=state.q.population;$('run').value=state.q.run||'';$('wafer').value=state.q.wafer||'';refreshAll().catch(fail);}
document.getElementById('filename').textContent=boot.manifest.source.split(/[\\/]/).pop();$('filename').title=boot.manifest.source;$('counts').textContent=`${T('Attempts')}: ${boot.manifest.attempts} · ${T('Latest')}: ${boot.manifest.population_counts?.latest||0} · ${T('Unresolved')}: ${boot.manifest.population_counts?.unresolved_latest||0} · ${T('Measurements')}: ${boot.manifest.measurements}${boot.offline?' · '+T(boot.scope==='summary'?'Summary snapshot':'Offline selection')+(boot.rows?' · '+boot.rows.length+' '+T('Captured rows'):''):''}`;
for(const run of boot.manifest.runs)$('run').add(new Option(`${run.id} · ${run.job} · ${utc(run.start)}`,run.id));for(const w of[...new Set(boot.manifest.wafers.filter(Boolean))])$('wafer').add(new Option(w,w));
for(const id of['run','wafer','population'])$(id).onchange=()=>{state.q[id]=id==='run'?$('run').value?Number($('run').value):null:id==='wafer'?$('wafer').value||null:$('population').value;refreshAll().catch(fail);};
$('nav-search').oninput=()=>navigation().catch(fail);$('add').onclick=showIn;$('reset').onclick=()=>{state.q.excluded_devices=[];state.q.excluded_measurements=[];state.q.alerts={};state.selection={tests:[],attempts:[],hard_bins:[],soft_bins:[]};for(const p of state.panes){p.filters={};p.values={};p.selected=[];}refreshAll().catch(fail);};$('save').onclick=()=>download('viewer-session.json',JSON.stringify(session(),null,2));$('load').onclick=()=>$('session-file').click();$('session-file').onchange=async e=>{try{const f=e.target.files[0];if(f.size>2*1024*1024)throw Error(T('Session exceeds 2 MiB'));restore(JSON.parse(await f.text()));}catch(e){fail(e);}};
$('export').onclick=()=>{const d=modal('Export HTML',`<p>${esc(T('One self-contained file for sharing. Maximum attachment size is enforced by the local viewer.'))}</p><div id="export-actions"></div>`);for(const scope of['selection','summary'])d.querySelector('#export-actions').append(button(scope==='selection'?'Current analysis selection':'Summary snapshot',async()=>{try{const q={...state.q,...state.selection};const layout=session();layout.panes=layout.panes.map(p=>({...p,snapshot_query:paneQuery(p)}));const html=await api('export',{query:q,scope,layout});download('stdf-viewer-'+scope+'.html',html,'text/html');d.close();}catch(e){fail(e);}}));};
window.addEventListener('report-ui-change',()=>{mountAll();refreshAll().catch(fail);});
if(boot.offline){$('population').value=state.q.population;$('population').disabled=true;if(boot.scope==='summary'){$('run').disabled=true;$('wafer').disabled=true;}}
let saved;try{saved=JSON.parse(localStorage.getItem('zstdf-viewer-'+boot.manifest.source_hash)||'null');}catch{}if(boot.session){const saved=clone(boot.session);if(boot.scope==='summary')saved.panes=saved.panes.filter(p=>!['measurements','devices','records','timing','ffc'].includes(p.kind));if(!saved.panes.length){addPane(boot.scope==='summary'?'histogram':'measurements');navigation().catch(fail);}else restore(saved);}else if(saved&&!boot.offline){try{restore(saved);}catch{addPane();navigation().catch(fail);}}else{addPane(boot.scope==='summary'?'histogram':'measurements');navigation().catch(fail);}
new ResizeObserver(entries=>{if(innerWidth>800)$('workspace').style.gridTemplateColumns=`${Math.min(650,Math.max(220,entries[0].contentRect.width+2))}px minmax(400px,1fr)`;}).observe($('navigation'));
window.Viewer={state,api,addPane,refreshAll,session,restore,offlinePlot};
})();
