// Copyright 2026 zstdf contributors. SPDX-License-Identifier: Apache-2.0
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '../examples/ftr-patterns/generated');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1536, height: 1080 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(pathToFileURL(path.join(root, 'report.html')).href);
    const cells = async pattern => {
      const row = page.locator('#fp-table tbody tr').filter({ has: page.getByRole('button', { name: pattern, exact: true }) });
      return row.locator('td').allTextContents();
    };
    assert.match(await page.locator('#fp-kpis').innerText(), /43/);
    assert.match(await page.locator('#fp-kpis').innerText(), /78.05%/);
    assert.equal(await page.locator('#fp-table tbody tr').count(), 5);
    assert.deepEqual((await cells('scan/core_at_speed')).slice(1), ['15','10','5','0','0','0','66.67','33.33','55.56','55.56']);
    assert.equal((await cells('optional/not_executed'))[7], 'N/A');
    assert.equal((await cells('memory/mbist'))[6], '1');
    assert.match(await page.locator('#fp-sources').textContent(), /1 unique.*2 source paths/);
    await page.getByRole('button', { name: 'scan/core_at_speed', exact: true }).click();
    assert.equal(await page.locator('#fp-detail-body tr').count(), 2);
    assert.match(await page.locator('#fp-detail-paths').innerText(), /patterns.stdf.gz/);
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await page.locator('#fp-site').selectOption(JSON.stringify('1/1'));
    assert.equal((await cells('scan/core_at_speed'))[1], '9');
    await page.locator('#fp-test').selectOption(JSON.stringify('102'));
    assert.equal(await page.locator('#fp-table tbody tr').count(), 1);
    await page.locator('#fp-reset').click();
    await page.locator('#fp-search').fill('no such pattern');
    assert.match(await page.locator('#fp-table tbody').innerText(), /No matching/);
    assert.doesNotMatch(await page.locator('#fp-kpis').innerText(), /NaN|Infinity/);
    await page.locator('#fp-reset').click();
    let downloadPromise = page.waitForEvent('download'); await page.locator('#fp-csv').click();
    let download = await downloadPromise; const csv = fs.readFileSync(await download.path(), 'utf8');
    assert.equal(csv.split('\r\n').length, 6); assert.match(csv, /scan\/core_at_speed/);
    downloadPromise = page.waitForEvent('download'); await page.locator('#fp-json').click(); download = await downloadPromise;
    const evidence = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
    assert.equal(evidence.schema, 'ftr-patterns-v1'); assert.equal(evidence.sources.length, 1);
    assert.equal(evidence.sources[0].groups.reduce((n,g)=>n+g.attempts,0),43);
    await page.screenshot({ path: path.join(root, 'report-desktop.png'), fullPage: true });
    await page.setViewportSize({ width:390,height:844 });
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path:path.join(root,'report-mobile.png'),fullPage:true });
    await page.setViewportSize({width:1536,height:1080});
    await page.goto(pathToFileURL(path.join(root,'dashboard.html')).href);
    await page.locator('.tab[data-tab="pareto"]').click();
    assert.equal(await page.locator('.tab[data-tab="ftr-patterns"]').count(),0);
    assert.equal(await page.locator('#pareto #fp').count(),1);
    assert.ok(await page.locator('#fp-table').isVisible());
    await page.locator('#search').fill('unrelated measurement filter');
    assert.equal(await page.locator('#fp-table tbody tr').count(),5);
    await page.getByRole('button',{name:'Overview',exact:true}).click();
    assert.ok(!await page.locator('#fp-table').isVisible());
    await page.locator('.tab[data-tab="pareto"]').click();
    assert.equal(await page.locator('.tab[data-tab="ftr-patterns"]').count(),0);
    assert.equal(await page.locator('#pareto #fp').count(),1);
    await page.screenshot({path:path.join(root,'dashboard-desktop.png'),fullPage:true});
    const datasetReport=path.join(root,'dataset-dashboard.html');
    if(fs.existsSync(datasetReport)) {
      await page.goto(pathToFileURL(datasetReport).href);
      await page.locator('.tab[data-tab="pareto"]').click();
    assert.equal(await page.locator('.tab[data-tab="ftr-patterns"]').count(),0);
    assert.equal(await page.locator('#pareto #fp').count(),1);
      assert.equal(await page.locator('#fp-table tbody tr').count(),5);
      await page.locator('#lot-select').selectOption('1');
      assert.equal(await page.locator('#fp-table tbody tr').count(),5);
      assert.match(await page.locator('#fp-kpis').innerText(),/78.05%/);
    }
    // Exercise pagination and script-safe rendering with an expanded synthetic report payload.
    const source=evidence.sources[0]; source.groups=Array.from({length:205},(_,i)=>({...source.groups[0],pattern:'PAT_'+String(i).padStart(3,'0'),attempts:1,pass:1,fail:0,unknown:0,not_executed:0,alarms:0}));
    source.groups[0].pattern='</script><img src=x onerror=alert(1)>';
    source.groups[1].pattern='=1+1';
    source.groups[2].pattern='Pass';
    const html=fs.readFileSync(path.join(root,'report.html'),'utf8').replace(/(<script type="application\/json" id="fp-data">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+JSON.stringify(evidence).replace(/</g,'\\u003c')+b);
    const expanded=path.join(root,'pagination-test.html');fs.writeFileSync(expanded,html);
    await page.goto(pathToFileURL(expanded).href);
    await page.locator('#report-language').selectOption('zh');
    await page.locator('#fp-search').fill('Pass');
    assert.equal(await page.locator('#fp-table tbody button').textContent(),'Pass');
    await page.locator('#fp-search').fill('');
    await page.locator('#report-language').selectOption('en');
    assert.equal(await page.locator('#fp-table tbody tr').count(),100);
    await page.locator('#fp-next').click();await page.locator('#fp-next').click();
    assert.equal(await page.locator('#fp-table tbody tr').count(),5);
    assert.equal(await page.locator('#fp img').count(),0);
    downloadPromise=page.waitForEvent('download');await page.locator('#fp-csv').click();download=await downloadPromise;
    const all=fs.readFileSync(await download.path(),'utf8');assert.equal(all.split('\r\n').length,206);assert.match(all, /'=1\+1/);
    await page.locator('#fp-search').fill('PAT_204');assert.equal(await page.locator('#fp-table tbody tr').count(),1);
    await page.locator('#fp-reset').click();
    await page.locator('#fp-table th button').filter({hasText:'VECT_NAM'}).click();
    assert.equal(await page.locator('#fp-table th').first().getAttribute('aria-sort'),'ascending');
    assert.deepEqual(errors,[]);
    console.log('FTR browser checks passed: counts, yield, deduplication, filters, details, sort, pagination, exports, mobile, safe names, dashboard integration.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
